import json
import os
import re
from pathlib import Path

from dotenv import load_dotenv

from .llm_client import LLMClient
from .state import BuilderState


def get_llm_client():
    load_dotenv()
    local_url = os.getenv("LOCAL_LLM_URL")
    if local_url:
        model_name = os.getenv("MODEL_NAME", "local-model")
        return LLMClient(api_key="local", base_url=local_url, model=model_name)
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise OSError("Set either OPENAI_API_KEY or LOCAL_LLM_URL")
    return LLMClient(api_key=api_key)

def load_workflow_node(state: BuilderState) -> BuilderState:
    content = Path(state.workflow_path).read_text()
    return state.model_copy(update={"workflow_content": content})

def generate_plan_node(state: BuilderState) -> BuilderState:
    llm = get_llm_client()
    
    tools = """Available tools:
- shell.echo: Print text. args: text to print
- shell.date: Get date/time. args: format string quoted
- shell.xargs: Execute with piped input. args: command
- exec.curl: HTTP requests. args: URL and options
- user.ask: Ask user a question. args: question text"""

    plan_instructions = """Break the workflow into steps with tool selection.
Output JSON with steps array. Each step has: order, description, tool, args.
Use {step_N} for data flow between steps."""

    if state.user_feedback:
        prompt = f"""Generate a revised execution plan incorporating user feedback: {state.user_feedback}

Workflow:
{state.workflow_content}

{tools}
{plan_instructions}
"""
    else:
        prompt = f"""Generate an execution plan for this workflow:

{state.workflow_content}

{tools}
{plan_instructions}
"""

    plan = llm.chat([{"role": "user", "content": prompt}], temperature=0.7, max_tokens=1024)
    return state.model_copy(update={"llm_plan": plan})


def show_plan_node(state: BuilderState) -> BuilderState:
    print("\nPlan (generated by LLM):")
    print(state.llm_plan)
    
    try:
        json_match = re.search(r'```json\s*(.*?)\s*```', state.llm_plan, re.DOTALL)
        json_str = json_match.group(1) if json_match else state.llm_plan
        plan_json = json.loads(json_str)
        steps = plan_json.get("steps", [])
        print("\nSteps:")
        for step in steps:
            print(f"  {step.get('order', '?')}. {step.get('description', 'N/A')} [{step.get('tool', 'N/A')}]")
    except (json.JSONDecodeError, KeyError) as e:
        print(f"\n(Unable to parse plan JSON for display: {e})")
    
    return state.model_copy(update={"approved": False})

def wait_for_approval_node(state: BuilderState):
    from langgraph.types import interrupt
    response = interrupt({"type": "approval", "plan": state.llm_plan})
    
    if response in ["yes", "y", "approve"]:
        return state.model_copy(update={"approved": True})
    else:
        return state.model_copy(update={"approved": False, "user_feedback": response})

def generate_standardized_workflow(state: BuilderState) -> BuilderState:
    """Generate standardized workflow markdown from plan JSON."""
    json_match = re.search(r'```json\s*(.*?)\s*```', state.llm_plan, re.DOTALL)
    json_str = json_match.group(1) if json_match else state.llm_plan
    plan_json = json.loads(json_str)
    
    # Extract workflow title from original content
    title_match = re.match(r"^#\s+(.+)$", state.workflow_content, re.MULTILINE)
    if title_match:
        title = title_match.group(1)
    else:
        # Use first line as title if no explicit title
        first_line = state.workflow_content.split("\n")[0].strip()
        title = first_line if first_line else "Workflow"
    
    # Generate standardized workflow in original style
    standardized = f"# {title}\n\n"
    for step in plan_json.get("steps", []):
        standardized += f"## Step {step.get('order', '?')}: {step.get('description', '')}\n"
        standardized += f"- tool: {step.get('tool', '')}\n"
        standardized += f"- args: {step.get('args', '')}\n\n"
    
    return state.model_copy(update={"standardized_workflow": standardized})

def should_update_source(state: BuilderState):
    """Check if source file needs updating."""
    # Compare original workflow with generated plan
    json_match = re.search(r'```json\s*(.*?)\s*```', state.llm_plan, re.DOTALL)
    json_str = json_match.group(1) if json_match else state.llm_plan
    plan_json = json.loads(json_str)
    
    # Simple heuristic: if plan has different number of steps than original, changes were made
    original_steps = len(re.findall(r"^(\d+)\.", state.workflow_content, re.MULTILINE))
    plan_steps = len(plan_json.get("steps", []))
    
    return original_steps != plan_steps

def ask_update_source_node(state: BuilderState):
    """Ask user if they want to update source file."""
    from langgraph.types import interrupt
    response = interrupt({"type": "update_source", "question": "Update source file with changes?"})
    
    if response in ["yes", "y"]:
        return state.model_copy(update={"update_source": True})
    return state.model_copy(update={"update_source": False})

def update_source_node(state: BuilderState) -> BuilderState:
    """Write standardized workflow back to source file."""
    Path(state.workflow_path).write_text(state.standardized_workflow)
    print(f"Updated source file: {state.workflow_path}")
    return state

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, StateGraph


def should_approve_or_check_update(state: BuilderState):
    if not state.approved:
        return "revise"
    if should_update_source(state):
        return "ask_update"
    return "end"

def compile_builder_workflow():
    workflow = StateGraph(BuilderState)
    
    workflow.add_node("load_workflow", load_workflow_node)
    workflow.add_node("generate_plan", generate_plan_node)
    workflow.add_node("show_plan", show_plan_node)
    workflow.add_node("wait_for_approval", wait_for_approval_node)
    workflow.add_node("generate_standardized", generate_standardized_workflow)
    workflow.add_node("ask_update_source", ask_update_source_node)
    workflow.add_node("update_source", update_source_node)
    
    workflow.set_entry_point("load_workflow")
    workflow.add_edge("load_workflow", "generate_plan")
    workflow.add_edge("generate_plan", "show_plan")
    workflow.add_edge("show_plan", "wait_for_approval")
    workflow.add_conditional_edges("wait_for_approval", should_approve_or_check_update, {
        "revise": "generate_plan",
        "ask_update": "ask_update_source",
        "end": END
    })
    workflow.add_conditional_edges("ask_update_source", lambda s: "generate" if s.update_source else "end", {
        "generate": "generate_standardized",
        "end": END
    })
    workflow.add_edge("generate_standardized", "update_source")
    workflow.add_edge("update_source", END)
    
    checkpointer = InMemorySaver()
    return workflow.compile(checkpointer=checkpointer)