import json
import re
import uuid
from pathlib import Path
from .builder import compile_builder_workflow, generate_plan_node
from .compiler import compile_to_langgraph
from .state import BuilderState
from langgraph.types import Command
from langgraph.checkpoint.memory import InMemorySaver


class Agent:
    """
    OpenShip Agent - orchestrates workflow building and execution.
    
    Encapsulates the builder and executor workflows, providing a clean API
    for CLI, web API, and other interfaces.
    """
    
    def __init__(self):
        self.workflow = None
        self.workflow_path = None
        self.graph = None
        self.plan = None
        self.builder = compile_builder_workflow()
        self.builder_config = {"configurable": {"thread_id": f"builder-{uuid.uuid4()}"}}
    
    def load_workflow(self, path: str):
        """Load a workflow markdown file."""
        self.workflow_path = path
        self.workflow = Path(path).read_text()
        return self.workflow
    
    def generate_plan(self, feedback=None):
        """
        Generate or regenerate the execution plan using LLM.
        
        Args:
            feedback: Optional user feedback for plan revision
        
        Returns:
            The generated plan JSON string
        """
        state = BuilderState(
            workflow_path="",
            workflow_content=self.workflow,
            user_feedback=feedback or ""
        )
        
        result = generate_plan_node(state)
        self.plan = result.llm_plan
        return self.plan

    def build_workflow(self):
        """
        Run the complete builder workflow including approval loop and source update check.
        
        Returns:
            The builder state with approved plan and potentially updated source
        """
        from langgraph.types import Command
        
        state = BuilderState(
            workflow_path=self.workflow_path,
            workflow_content=self.workflow
        )
        
        result = self.builder.invoke(state, self.builder_config)
        
        while "__interrupt__" in result:
            interrupt_info = result["__interrupt__"][0]
            interrupt_type = interrupt_info.value.get("type", "")
            
            if interrupt_type == "approval":
                print("\nPlan (generated by LLM):")
                print(interrupt_info.value.get("plan", ""))
                response = input("\nApprove plan? [yes/no]: ").lower().strip()
                result = self.builder.invoke(Command(resume=response), self.builder_config)
            elif interrupt_type == "update_source":
                response = input(f"\n{interrupt_info.value.get('question', 'Update source?')} [yes/no]: ").lower().strip()
                result = self.builder.invoke(Command(resume=response), self.builder_config)
            else:
                print(f"\n[interrupt] {interrupt_info.value}")
                response = input("Response: ")
                result = self.builder.invoke(Command(resume=response), self.builder_config)
        
        # Result is a dict with state values
        if isinstance(result, dict):
            self.plan = result.get("llm_plan", "")
            return BuilderState(**result)
        
        self.plan = result.llm_plan
        return result
    
    def parse_plan(self):
        """Parse the plan JSON string to a dict."""
        json_match = re.search(r'```json\s*(.*?)\s*```', self.plan, re.DOTALL)
        json_str = json_match.group(1) if json_match else self.plan
        return json.loads(json_str)
    
    def show_plan(self):
        """Display the current plan to the user."""
        print("\nPlan (generated by LLM):")
        print(self.plan)
        
        try:
            plan_json = self.parse_plan()
            steps = plan_json.get("steps", [])
            print("\nSteps:")
            for step in steps:
                print(f"  {step.get('order', '?')}. {step.get('description', 'N/A')} [{step.get('tool', 'N/A')}]")
        except Exception as e:
            print(f"\n(Unable to parse plan JSON for display: {e})")
    
    def compile_graph(self, plan_json=None):
        """
        Compile a plan to LangGraph.
        
        Args:
            plan_json: Optional plan JSON dict. Uses self.plan if not provided.
        
        Returns:
            The compiled LangGraph
        """
        if plan_json is None:
            if not self.plan:
                raise ValueError("No plan available")
            plan_json = self.parse_plan()
        
        checkpointer = InMemorySaver()
        self.graph = compile_to_langgraph(plan_json, checkpointer=checkpointer)
        return self.graph
    
    def execute(self, inputs=None):
        """
        Execute the compiled graph with human-in-the-loop.
        
        Args:
            inputs: Optional input values
        
        Returns:
            The execution results
        """
        if not self.graph:
            self.compile_graph()
        
        if inputs is None:
            inputs = {}
        
        config = {"configurable": {"thread_id": f"exec-{uuid.uuid4()}"}}
        result = self.graph.invoke({"inputs": inputs, "outputs": {}}, config)
        
        # Handle interrupts
        while "__interrupt__" in result:
            interrupt_info = result["__interrupt__"][0]
            question = interrupt_info.value.get("question", "Question from agent:")
            print(f"\n[Agent asks] {question}")
            user_response = input("Your response: ")
            print(f"  [Resuming with: {user_response}]")
            result = self.graph.invoke(Command(resume=user_response), config)
        
        return result