import json
import re
import uuid
from pathlib import Path
from .builder import compile_builder_workflow
from .compiler import compile_to_langgraph
from .state import BuilderState
from langgraph.types import Command
from langgraph.checkpoint.memory import InMemorySaver


class Agent:
    """
    OpenShip Agent - orchestrates workflow building and execution.
    
    Encapsulates the builder and executor workflows, providing a clean API
    for CLI, web API, and other interfaces.
    """
    
    def __init__(self):
        self.workflow = None
        self.graph = None
        self.plan = None
        self.builder = compile_builder_workflow()
        self.builder_config = {"configurable": {"thread_id": f"builder-{uuid.uuid4()}"}}
    
    def load_workflow(self, path: str):
        """Load a workflow markdown file."""
        self.workflow = Path(path).read_text()
        return self.workflow
    
    def generate_plan(self, feedback=None):
        """
        Generate or regenerate the execution plan using LLM.
        
        Args:
            feedback: Optional user feedback for plan revision
        
        Returns:
            The generated plan JSON string
        """
        # Reset state for new plan generation
        state = BuilderState(
            workflow_path="",
            workflow_content=self.workflow,
            user_feedback=feedback or ""
        )
        
        # Use builder workflow's generate_plan node directly
        from .builder import generate_plan_node
        result = generate_plan_node(state)
        self.plan = result.llm_plan
        return self.plan
    
    def show_plan(self):
        """Display the current plan to the user."""
        print("\nPlan (generated by LLM):")
        print(self.plan)
        
        try:
            json_match = re.search(r'```json\s*(.*?)\s*```', self.plan, re.DOTALL)
            json_str = json_match.group(1) if json_match else self.plan
            plan_json = json.loads(json_str)
            steps = plan_json.get("steps", [])
            print("\nSteps:")
            for step in steps:
                print(f"  {step.get('order', '?')}. {step.get('description', 'N/A')} [{step.get('tool', 'N/A')}]")
        except Exception as e:
            print(f"\n(Unable to parse plan JSON for display: {e})")
    
    def compile_graph(self, plan=None):
        """
        Compile a plan to LangGraph.
        
        Args:
            plan: Optional plan JSON string. Uses self.plan if not provided.
        
        Returns:
            The compiled LangGraph
        """
        plan_str = plan or self.plan
        if not plan_str:
            raise ValueError("No plan available")
        
        # Parse plan JSON
        json_match = re.search(r'```json\s*(.*?)\s*```', plan_str, re.DOTALL)
        json_str = json_match.group(1) if json_match else plan_str
        plan_json = json.loads(json_str)
        
        checkpointer = InMemorySaver()
        self.graph = compile_to_langgraph(plan_json, checkpointer=checkpointer)
        return self.graph
    
    def execute(self, inputs=None):
        """
        Execute the compiled graph with human-in-the-loop.
        
        Args:
            inputs: Optional input values
        
        Returns:
            The execution results
        """
        if not self.graph:
            self.compile_graph()
        
        if inputs is None:
            inputs = {}
        
        config = {"configurable": {"thread_id": f"exec-{uuid.uuid4()}"}}
        result = self.graph.invoke({"inputs": inputs, "outputs": {}}, config)
        
        # Handle interrupts
        while "__interrupt__" in result:
            interrupt_info = result["__interrupt__"][0]
            question = interrupt_info.value.get("question", "Question from agent:")
            print(f"\n[Agent asks] {question}")
            user_response = input("Your response: ")
            print(f"  [Resuming with: {user_response}]")
            result = self.graph.invoke(Command(resume=user_response), config)
        
        return result