import os
from pathlib import Path
from dotenv import load_dotenv
from .state import BuilderState
from .llm_client import LLMClient

def get_llm_client():
    load_dotenv()
    local_url = os.getenv("LOCAL_LLM_URL")
    if local_url:
        model_name = os.getenv("MODEL_NAME", "local-model")
        return LLMClient(api_key="local", base_url=local_url, model=model_name)
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise EnvironmentError("Set either OPENAI_API_KEY or LOCAL_LLM_URL")
    return LLMClient(api_key=api_key)

def load_workflow_node(state: BuilderState) -> BuilderState:
    content = Path(state.workflow_path).read_text()
    return state.model_copy(update={"workflow_content": content})

def generate_plan_node(state: BuilderState) -> BuilderState:
    llm = get_llm_client()
    
    tools = """Available tools:
- shell.echo: Print text. args: text to print
- shell.date: Get date/time. args: format string quoted
- shell.xargs: Execute with piped input. args: command
- exec.curl: HTTP requests. args: URL and options
- user.ask: Ask user a question. args: question text"""

    plan_instructions = """Break the workflow into steps with tool selection.
Output JSON with steps array. Each step has: order, description, tool, args.
Use {step_N} for data flow between steps."""

    if state.user_feedback:
        prompt = f"""Generate a revised execution plan incorporating user feedback: {state.user_feedback}

Workflow:
{state.workflow_content}

{tools}
{plan_instructions}
"""
    else:
        prompt = f"""Generate an execution plan for this workflow:

{state.workflow_content}

{tools}
{plan_instructions}
"""

    plan = llm.chat([{"role": "user", "content": prompt}], temperature=0.7, max_tokens=1024)
    return state.model_copy(update={"llm_plan": plan})

import json
import re

def show_plan_node(state: BuilderState) -> BuilderState:
    print("\nPlan (generated by LLM):")
    print(state.llm_plan)
    
    try:
        json_match = re.search(r'```json\s*(.*?)\s*```', state.llm_plan, re.DOTALL)
        json_str = json_match.group(1) if json_match else state.llm_plan
        plan_json = json.loads(json_str)
        steps = plan_json.get("steps", [])
        print("\nSteps:")
        for step in steps:
            print(f"  {step.get('order', '?')}. {step.get('description', 'N/A')} [{step.get('tool', 'N/A')}]")
    except Exception as e:
        print(f"\n(Unable to parse plan JSON for display: {e})")
    
    return state.model_copy(update={"approved": False})

def wait_for_approval_node(state: BuilderState):
    from langgraph.types import interrupt
    response = interrupt({"type": "approval", "plan": state.llm_plan})
    
    if response in ["yes", "y", "approve"]:
        return state.model_copy(update={"approved": True})
    else:
        return state.model_copy(update={"approved": False, "user_feedback": response})

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import InMemorySaver

def should_approve(state: BuilderState):
    if state.approved:
        return "approved"
    return "revise"

def compile_builder_workflow():
    workflow = StateGraph(BuilderState)
    
    workflow.add_node("load_workflow", load_workflow_node)
    workflow.add_node("generate_plan", generate_plan_node)
    workflow.add_node("show_plan", show_plan_node)
    workflow.add_node("wait_for_approval", wait_for_approval_node)
    
    workflow.set_entry_point("load_workflow")
    workflow.add_edge("load_workflow", "generate_plan")
    workflow.add_edge("generate_plan", "show_plan")
    workflow.add_edge("show_plan", "wait_for_approval")
    workflow.add_conditional_edges("wait_for_approval", should_approve, {
        "approved": END,
        "revise": "generate_plan"
    })
    
    checkpointer = InMemorySaver()
    return workflow.compile(checkpointer=checkpointer)