import argparse
from .agent import Agent


def main():
    parser = argparse.ArgumentParser(description="OpenShip Workflow PoC")
    parser.add_argument("workflow", help="Path to workflow markdown file")
    args = parser.parse_args()

    agent = Agent()
    workflow = agent.load_workflow(args.workflow)
    print(f"Loaded workflow: {workflow['title']}")

    # Generate plan using LLM
    print("\nGenerating plan with LLM...")
    plan = agent.generate_plan()
    print("Plan generated.")

    # Approval loop with LLM-based regeneration
    while True:
        print("\nPlan (generated by LLM):")
        print(plan)

        response = input("\nApprove plan? [yes/no]: ").lower().strip()
        if response == "yes" or response == "y":
            break
        elif response == "no" or response == "n":
            feedback = input("What would you like to change? ")
            print("Regenerating plan with LLM based on feedback...")
            plan = agent.generate_plan(feedback)
            print("Plan regenerated.")
        else:
            print("Invalid response. Please enter 'yes' or 'no'.")

    print("\nExecuting workflow...")
    agent.compile_graph(plan)
    result = agent.execute()
    print("\nResults:")
    for step_order, output in result["outputs"].items():
        print(f"  Step {step_order}: {output}")


if __name__ == "__main__":
    main()