import argparse
import sys
from .agent import Agent
from langgraph.types import Command


def main():
    parser = argparse.ArgumentParser(description="OpenShip Workflow PoC")
    parser.add_argument("workflow", help="Path to workflow markdown file")
    parser.add_argument("--show-thinking", action="store_true",
                        help="Stream LLM reasoning/thinking process to terminal")
    args = parser.parse_args()

    agent = Agent()
    workflow = agent.load_workflow(args.workflow)
    print(f"Loaded workflow from: {args.workflow}")

    # Generate plan using LLM
    if args.show_thinking:
        print("\nGenerating plan with LLM (streaming reasoning)...")
        plan_parts = []
        for chunk in agent.generate_plan_stream():
            sys.stdout.write(chunk)
            sys.stdout.flush()
            plan_parts.append(chunk)
        plan = "".join(plan_parts)
        print()  # Newline after streaming completes
    else:
        print("\nGenerating plan with LLM...")
        plan = agent.generate_plan()
        print("Plan generated.")

    # Approval loop with LLM-based regeneration
    while True:
        print("\nPlan (generated by LLM):")
        print(plan)

        # Also display as human-readable list
        try:
            import json
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', plan, re.DOTALL)
            json_str = json_match.group(1) if json_match else plan
            # Fix common JSON issues: unescaped quotes in args
            json_str = re.sub(r'"args":\s*"\+"([^"]*)"(\s*)"', r'"args": "+\1"', json_str)
            json_str = re.sub(r'"args":\s*"(\+[^"]*)"', r'"args": "\1"', json_str)
            plan_json = json.loads(json_str)
            steps = plan_json.get("steps", [])
            print("\nSteps:")
            for step in steps:
                print(f"  {step.get('order', '?')}. {step.get('description', 'N/A')} [{step.get('tool', 'N/A')}]")
        except Exception as e:
            print(f"\n(Unable to parse plan JSON for display: {e})")

        response = input("\nApprove plan? [yes/no]: ").lower().strip()
        if response == "yes" or response == "y":
            break
        elif response == "no" or response == "n":
            feedback = input("What would you like to change? ")
            if args.show_thinking:
                print("Regenerating plan with LLM based on feedback (streaming)...")
                plan_parts = []
                for chunk in agent.generate_plan_stream(feedback):
                    sys.stdout.write(chunk)
                    sys.stdout.flush()
                    plan_parts.append(chunk)
                plan = "".join(plan_parts)
                print()  # Newline after streaming completes
            else:
                print("Regenerating plan with LLM based on feedback...")
                plan = agent.generate_plan(feedback)
            print("Plan regenerated.")
        else:
            print("Invalid response. Please enter 'yes' or 'no'.")

    print("\nExecuting workflow...")
    agent.compile_graph(plan)

    # Execute with interrupt handling
    is_resuming = False
    while True:
        if is_resuming:
            # Resume from previous interrupt
            interrupt_info = result["__interrupt__"][0]
            question = interrupt_info.value["question"]
            print(f"\n[Agent asks] {question}")
            user_response = input("Your response: ")
            print(f"  [Resuming with: {user_response}]")
            result = agent.graph.invoke(Command(resume=user_response), agent.config)
        else:
            # Start new execution
            result = agent.graph.invoke({"inputs": {}, "outputs": {}}, agent.config)

        # Check if graph is paused at an interrupt
        if "__interrupt__" in result:
            is_resuming = True
            continue
        else:
            # Graph completed
            break

    print("\nResults:")
    if isinstance(result, dict):
        for step_order, output in result.get("outputs", {}).items():
            print(f"  Step {step_order}: {output}")
    else:
        print(f"  Result type: {type(result)}")
        print(f"  Result: {result}")


if __name__ == "__main__":
    main()